on:
  push:
    branches: [develop, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}
        run: |
          curl -X GET $WEBHOOK_URL